export type {
  // Error
  CurseForgeApiErrorPayload,
  // Enums (const objects)
  // (re-exported as values + types via the wildcard below)
  // Entities
  Pagination,
  GameAssets,
  Game,
  GameVersion,
  GameVersionsByType,
  GameVersionsByTypeV2,
  GameVersionType,
  Category,
  ModLinks,
  ModAuthor,
  ModAsset,
  SortableGameVersion,
  FileHash,
  FileIndex,
  FileModule,
  FileDependency,
  File,
  SocialLink,
  RatingDetails,
  ServerAffiliation,
  CurseForgeMod,
  FeaturedModsResponse,
  FingerprintMatch,
  FingerprintFuzzyMatch,
  FingerprintMatchesResult,
  FingerprintFuzzyMatchResult,
  FolderFingerprint,
  MinecraftGameVersion,
  MinecraftModLoaderIndex,
  MinecraftModLoaderVersion,
  // API responses
  GetGamesResponse,
  GetGameResponse,
  GetVersionsResponse,
  GetVersionsV2Response,
  GetVersionTypesResponse,
  GetCategoriesResponse,
  SearchModsResponse,
  GetModResponse,
  GetModsResponse,
  GetFeaturedModsResponse,
  GetModDescriptionResponse,
  GetModFileResponse,
  GetModFilesResponse,
  GetFilesResponse,
  GetModFileChangelogResponse,
  GetModFileDownloadURLResponse,
  GetFingerprintMatchesResponse,
  GetFingerprintFuzzyMatchesResponse,
  ApiResponseOfListOfMinecraftGameVersion,
  ApiResponseOfMinecraftGameVersion,
  ApiResponseOfListOfMinecraftModLoaderIndex,
  ApiResponseOfMinecraftModLoaderVersion,
  // Request bodies
  GetModsByIdsListRequestBody,
  GetFeaturedModsRequestBody,
  GetModFilesRequestBody,
  GetFingerprintMatchesRequestBody,
  GetFuzzyMatchesRequestBody,
  // Query params
  GetGamesParams,
  SearchModsParams,
  GetModFilesParams,
  GetModDescriptionParams,
  GetMinecraftModLoadersParams,
  // SDK internals
  RateLimitSnapshot,
  CurseForgeSDKOptions,
  RequestOptions,
} from "./api.js";

export {
  // Enum const objects (also usable as value namespaces)
  CoreApiStatus,
  CoreStatus,
  GameVersionStatus,
  GameVersionTypeStatus,
  HashAlgo,
  FileRelationType,
  FileReleaseType,
  FileStatus,
  ModLoaderType,
  ModLoaderInstallMethod,
  ModStatus,
  ModSearchSortField,
  AffiliationServiceType,
  RatingScore,
  SocialLinkType,
  PlatformType,
  PremiumType,
} from "./api.js";